# Minimal SearxNG configuration tailored for the MCP search module. The goal is
# to provide deterministic defaults that work in development and CI while
# keeping the list of enabled engines compliant with permissive licences.
use_default_settings: true

server:
  # Use a deterministic but sufficiently long default secret so the container
  # boots without requiring manual overrides during local development. The
  # sample value below is 48 characters long, satisfying SearxNG's minimum
  # length requirements while remaining safe to replace in production via
  # environment overrides or Docker secrets.
  secret_key: "please-change-me-please-change-me-please-change-me"
  port: 8080
  bind_address: "0.0.0.0"
  public_instance: false
  # The limiter requires a Valkey/Redis backend; keep it disabled in the
  # self-contained development stack to avoid depending on external services.
  limiter: false
  method: "auto"

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json

# Each engine defines a shortcut so SearxNG can register them without collisions.
engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
    timeout: 5.0
    categories:
      - general
      - news
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
    timeout: 5.0
    categories:
      - general
      - science
  - name: arxiv
    engine: arxiv
    shortcut: arx
    disabled: false
    timeout: 5.0
    categories:
      - science
      - files
  - name: github
    engine: github
    shortcut: gh
    disabled: false
    timeout: 5.0
    categories:
      - it
      - code
  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false
    timeout: 5.0
    categories:
      - general
      - images

ui:
  theme_args:
    header_logo: ""
  infinite_scroll: false

result_proxy:
  url: ""
  rewrite_result_links: false

categories_as_tabs:
  - general
  - news
  - science
  - it
  - files
  - images
