#!/usr/bin/env node
/**
 * Simple cleanup utility that removes build artifacts for both the root project and the graph-forge package.
 * We rely on Node's fs.rm to avoid additional dependencies while keeping the command idempotent.
 */
import { rm } from 'node:fs/promises';
import { resolve } from 'node:path';

/** Directories generated by build steps that should be purged before a fresh compilation. */
const TARGETS = [
  resolve('dist'),
  resolve('graph-forge', 'dist'),
  resolve('.turbo'),
  resolve('.tsbuildinfo')
];

async function removeTarget(target) {
  try {
    await rm(target, { recursive: true, force: true });
    console.log(`Removed ${target}`);
  } catch (error) {
    console.warn(`Unable to remove ${target}:`, error);
  }
}

async function main() {
  await Promise.all(TARGETS.map(removeTarget));
}

main().catch((error) => {
  console.error('Clean script failed', error);
  process.exitCode = 1;
});
