name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-typecheck-test:
    name: Build, typecheck and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application bundles
        run: npm run build

      - name: Type-check sources and tests
        run: npm run typecheck

      - name: Run lint suite
        run: npm run lint

      - name: Run full test pipeline (TAP)
        run: |
          set -euo pipefail
          mkdir -p artifacts
          npm run test | tee artifacts/tap.txt

      - name: Upload TAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tap-report
          path: artifacts/tap.txt
          if-no-files-found: warn

      - name: Upload unit test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: self-codex.test.log
          path: /tmp/self-codex.test.log
          if-no-files-found: warn
