# This GitHub Actions workflow maintains the guarantee that every change
# continues to build and pass unit tests on Node.js 20, matching the Cloud
# environment requirements described in AGENTS.md. Each step is documented to
# help future maintainers understand the rationale.
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and unit tests (Node 20)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Ensure the workflow always tests the current revision
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        # Align the CI runtime with the mandated Node >= 20 environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        # npm ci respects the lockfile and installs both prod and dev deps
        run: npm ci

      - name: Build TypeScript sources
        # Recreate the official build pipeline exactly as documented
        run: npm run build

      - name: Run unit test suite
        # Execute the Mocha-based unit test entry point required by the checklist
        run: npm run test:unit

  http-e2e:
    name: HTTP end-to-end (loopback allowed)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript sources
        run: npm run build

      - name: Run HTTP e2e suite
        run: npm run test:e2e:http
