# This GitHub Actions workflow enforces the build and quality gates described in AGENTS.md.
# It mirrors the local developer workflow: install dependencies, compile the TypeScript
# sources, lint the project, execute the full automated test suite, and publish coverage
# artefacts. An optional smoke job builds the Docker image and exercises the HTTP health
# probes to catch packaging regressions early.
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-verify:
    name: Build, lint, test, and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Compile TypeScript sources
        run: npm run build

      - name: Run linters
        run: npm run lint

      - name: Execute automated tests
        run: npm run test

      - name: Generate coverage report
        run: npm run coverage

      - name: Upload coverage artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage
            coverage/lcov-report
          if-no-files-found: warn

  docker-smoke:
    name: Build Docker image and probe HTTP endpoints
    runs-on: ubuntu-latest
    needs: build-and-verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build runtime image
        run: docker build --pull --tag self-codex-ci .

      - name: Launch container
        run: |
          docker run -d \
            --name mcp-smoke \
            -p 8765:8765 \
            -e MCP_HTTP_TOKEN=integration-token \
            -e MCP_LOG_REDACT=on \
            self-codex-ci \
            --http \
            --http-host 0.0.0.0 \
            --http-port 8765 \
            --http-path /mcp \
            --http-json on

      - name: Wait for readiness
        shell: bash
        run: |
          set -euo pipefail
          success=false
          for attempt in {1..20}; do
            if curl --fail --silent http://127.0.0.1:8765/healthz > /tmp/healthz.json; then
              success=true
              break
            fi
            sleep 3
          done
          if [ "$success" != "true" ]; then
            echo "Health probe failed after multiple attempts" >&2
            docker logs mcp-smoke || true
            exit 1
          fi
          cat /tmp/healthz.json

      - name: Probe readiness endpoint
        run: |
          curl --fail --silent \
            -H "Authorization: Bearer integration-token" \
            http://127.0.0.1:8765/readyz

      - name: Cleanup container
        if: always()
        run: docker rm -f mcp-smoke
