# CI workflow to guarantee build, lint, and test coverage on every push/PR.
name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  node-ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["18", "20"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript sources
        run: npm run build

      - name: Lint TypeScript projects
        run: npm run lint

      - name: Run test suite
        run: npm test
